/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exercicioestoque;

import java.util.Scanner;

public class App {
public static void main(String[] args) {
        Estoque estoque = new Estoque(); // Instância do estoque
        Scanner scanner = new Scanner(System.in);
        boolean running = true;

        while (running) {
            System.out.println("\n----- Sistema de Estoque -----");
            System.out.println("1. Adicionar Produto"            );
            System.out.println("2. Remover Produto"              );
            System.out.println("3. Consultar Quantidade"         );
            System.out.println("4. Produto Mais Estocado"        );
            System.out.println("5. Limpar Estoque"               );
            System.out.print("Escolha uma opcao: "               );

            int opcao = scanner.nextInt();
            scanner.nextLine(); // Consumir o "\n"

            switch (opcao) {
                case 1:
                    System.out.print("Digite o nome do produto: ");
                    String nomeAdicionar = scanner.nextLine();
                    System.out.print("Digite a quantidade: ");
                    int quantidadeAdicionar = scanner.nextInt();
                    estoque.adicionarProduto(nomeAdicionar, quantidadeAdicionar);
                    System.out.println("Produto adicionado!");
                    break;

                case 2:
                    System.out.print("Digite o nome do produto: ");
                    String nomeRemover = scanner.nextLine();
                    System.out.print("Digite a quantidade a remover: ");
                    int quantidadeRemover = scanner.nextInt();
                    try {
                        estoque.removerProduto(nomeRemover, quantidadeRemover);
                        System.out.println("Produto removido!");
                    } catch (IllegalArgumentException e) {
                        System.out.println("Erro: " + e.getMessage());
                    }
                    break;

                case 3:
                    System.out.print("Digite o nome do produto: ");
                    String nomeConsultar = scanner.nextLine();
                    try {
                        int quantidade = estoque.consultarQuantidade(nomeConsultar);
                        System.out.println("Quantidade de " + nomeConsultar + ": " + quantidade);
                    } catch (IllegalArgumentException e) {
                        System.out.println("Erro: " + e.getMessage());
                    }
                    break;

                case 4:
                    try {
                        String produtoMaisEstocado = estoque.produtoMaisEstocado();
                        System.out.println("Produto mais estocado: " + produtoMaisEstocado);
                    } catch (IllegalStateException e) {
                        System.out.println("Erro: " + e.getMessage());
                    }
                    break;

                case 5:
                    estoque.limparEstoque();
                    System.out.println("Estoque limpo!");
                    break;

                case 6:
                    System.out.println("\nProdutos no estoque:");
             

            }
        }
    }
}
